server:
  port: 3000
spring:
  application:
    name: redis-provider
  redis:
    host: 127.0.0.1
eureka:
  client:
    service-url:
      defaultZone: http://admin:enjoy@localhost:7001/eureka/
  instance:
    prefer-ip-address: true